"""v1.0.5

Revision ID: 270f076cd1ab
Revises: 25603c24d9b2
Create Date: 2017-10-28 00:59:58.363750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270f076cd1ab'
down_revision = '25603c24d9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
